const Listitems=[
    {
        "id":1,
        "Name":"Chicken Tikka Masala",
        "Category":"Non-veg",
        "Image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqqbT-GtmTTSr4QsluzCpLaVY5DxjQufxcCg&usqp=CAU",
        "Price":250,
        "quantity":[1,2,3,4,5],
    },
    {
        "id":2,
        "Name":"Egg kadai",
        "Category":"Non-veg",
        "Image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKpi8Kv23ZIHoyBlbirk2xB0UvUl2F4UjVgNdPBATNcAx4fHY9KHxqdrXjZ_BdROtOkCo&usqp=CAU",
        "Price":150,
        "quantity":[1,2,3,4,5],
    },  
    {
        "id":3,
        "Name":"Chicken Dum biryani",
        "Category":"Non-veg",
        "Image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRe-HRFpwjWMYD56Xsq2TO99eTBmegEuUhlzQ&usqp=CAU",
        "Price":180,
        "quantity":[1,2,3,4,5],
    },
     {
        "id":4,
        "Name":"Panner biryani",
        "Category":"veg",
        "Image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTA4x-4oWYFsshyI8dRSko3eAHSzv7AolL0XA&usqp=CAU",
        "Price":190,
        "quantity":[1,2,3,4,5],
    },
    {
        "id":5,
        "Name":"Mutton Dum biryani",
        "Category":"Non-veg",
        "Image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtET0c-w6TooIu03WMOYzHoC7cmm26dJxAPA&usqp=CAU",
        "Price":230,
        "quantity":[1,2,3,4,5],
    },
     {
        "id":6,
        "Name":"Veg Dum biryani",
        "Category":"veg",
        "Image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRj0d3cjoB7PjdgxXD5oXp_JHz4xdVIirIpBg&usqp=CAU",
        "Price":130,
        "quantity":[1,2,3,4,5],
    },
     {
        "id":7,
        "Name":"Chicken kadai",
        "Category":"Non-veg",
        "Image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT-4pva3LP401fQjZIzxjdNtllytJpD6q-WQ&usqp=CAU",
        "Price":220,
        "quantity":[1,2,3,4,5],
    },
    {
        "id":8,
        "Name":"Mutton keema Masala",
        "Category":"Non-veg",
        "Image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwIT7JrsFvTE4lOIBeGeqGzbl9cCADcO-ETg&usqp=CAU",
        "Price":230,
        "quantity":[1,2,3,4,5],
    },
    {
        "id":9,
        "Name":"Fish Tikka Masala",
        "Category":"Non-veg",
        "Image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSvT5jHTK4FYNn5NmrgsVDA061XWdtMN6_dA&usqp=CAU",
        "Price":250,
        "quantity":[1,2,3,4,5],
    },
    {
        "id":10,
        "Name":"Chana Masala",
        "Category":"veg",
        "Image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRNfJ4Q0b-1_cleO82vWQowzPdC3x_YaJbqA&usqp=CAU",
        "Price":130,
        "quantity":[1,2,3,4,5],
    },
    {
        "id":11,
        "Name":"Shahi Panner",
        "Category":"veg",
        "Image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXltUGf_HF7ATt4VWmCol_RiAD1SVCMAJ7wQ&usqp=CAU",
        "Price":250,
        "quantity":[1,2,3,4,5],
    },
    {
        "id":12,
        "Name":"Panner Bhurji",
        "Category":"veg",
        "Image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9q3rByJiE0PEDvZscUqB4u-zxA7kglDFeBg&usqp=CAU",
        "Price":230,
        "quantity":[1,2,3,4,5],
    },
    {
        "id":13,
        "Name":"Mutton chaap masala",
        "Category":"Non-veg",
        "Image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLVyVuGvz6yEEMZHTyk9fkq7YNkPekL9_iJg&usqp=CAU",
        "Price":340,
        "quantity":[1,2,3,4,5],
    },
    {
        "id":14,
        "Name":"Mutton Tawa",
        "Category":"Non-veg",
        "Image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBfi5mRqWif8DGLcGkq5njF9cX9XF3-qR1dA&usqp=CAU",
        "Price":350,
        "quantity":[1,2,3,4,5],
    },
    {
        "id":15,
        "Name":"Fish Finger masala",
        "Category":"Non-veg",
        "Image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR95afX0NSYxusiqBREF2uio9CmxDKraVKPbA&usqp=CAU",
        "Price":310,
        "quantity":[1,2,3,4,5],
    },
    {
        "id":16,
        "Name":"Chicken Palak Masala",
        "Category":"Non-veg",
        "Image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSm0TCjQ6Kyq3zHcKrRCAkHx8slGsclbHqcow&usqp=CAU",
        "Price":220,
        "quantity":[1,2,3,4,5],
    },
    {
        "id":17,
        "Name":"Mutton Nargisi Masala",
        "Category":"Non-veg",
        "Image":"https://www.archanaskitchen.com/images/archanaskitchen/1-Author/usashis-gmail.com/Nargisi_Kofta_CurrySpicy_scotched_egg_curry_400.jpg",
        "Price":340,
        "quantity":[1,2,3,4,5],
    },
    {
        "id":18,
        "Name":"Mutton mirchi korma",
        "Category":"Non-veg",
        "Image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSC4u9Z4ZGalR8eZPDx4jcI5wFWkMl-hEBC-A&usqp=CAU",
        "Price":200,
        "quantity":[1,2,3,4,5],
    },
    {
        "id":19,
        "Name":"Fish Do-Pyaza",
        "Category":"Non-veg",
        "Image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXPN22c7wIdDG8BYD2t3oUwaqu0bcIeCnnig&usqp=CAU",
        "Price":260,
        "quantity":[1,2,3,4,5],
    },
    {
        "id":20,
        "Name":"MUshroom khada Masala",
        "Category":"veg",
        "Image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1dRbWlNUuDiqnxzWibPgvUmR5V5Zmfpi7oQ&usqp=CAU",
        "Price":180,
        "quantity":[1,2,3,4,5],
    },

   
    

]

export default Listitems